# Generated by Django 3.2 on 2022-06-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_id',
            new_name='stripe_pid',
        ),
    ]
