# Generated by Django 3.2 on 2022-07-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='body_part',
            new_name='bodypart',
        ),
    ]
