# Generated by Django 3.2 on 2022-06-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name_plural': 'Product_Categories'},
        ),
    ]
